# Generated by Django 3.1.4 on 2021-06-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='access_Token',
            new_name='access_token',
        ),
    ]
