# Generated by Django 3.1.4 on 2021-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210530_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_name',
            field=models.CharField(default='host', max_length=20),
        ),
    ]
